#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -N cont_200
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
Rscript ./continuous_model_200.R > continuous_model_200.out