#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -N cont_bootstrap
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
Rscript ./bootstrap.R > bootstrap.out