#!/bin/sh
#PBS -l walltime=12:00:00
#PBS -N binc_bootstrap3
#PBS -l nodes=1:ppn=24

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
# Rscript ./binary_c_bootstrap.R > binary_c_bootstrap.out

torque-launch cmds3