#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -N binary_modelc500_em
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
Rscript ./binary_modelc500.R > binary_modelc500.out