#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -N binc_bootstrap
#PBS -l nodes=1:ppn=24

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
# Rscript ./binary_c_bootstrap.R > binary_c_bootstrap.out
# Rscript ./binc_1700.R > binc_1700.out

torque-launch cmds4