#!/bin/sh
#PBS -l walltime=4:00:00
#PBS -N binr_bootstrap
#PBS -l nodes=1:ppn=24

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
# Rscript ./binary_r_bootstrap.R > binary_r_bootstrap.out

torque-launch cmds