#!/bin/sh
#PBS -l walltime=48:00:00
#PBS -N count_aim3_nbin
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
torque-launch cmds2