#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -N binary_aim3
#PBS -l nodes=1:ppn=4

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
torque-launch cmds