#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -N aim2_data_simple
#PBS -l nodes=1:ppn=1

# Load R
module load r/4.1.2

# change to directory where 'qsub' was called
cd $PBS_O_WORKDIR

# run my program
Rscript ./aim2_simple.R > aim2data_simple.out